import React, { createContext, useState, useContext, useEffect } from 'react';
import { useLocation } from 'react-router-dom';

const LanguageContext = createContext();

export const useLanguage = () => useContext(LanguageContext);

export const LanguageProvider = ({ children }) => {
  const location = useLocation();
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('appLanguage') || 'en';
  });

  useEffect(() => {
    localStorage.setItem('appLanguage', language);
  }, [language]);

  // Sync with URL on change
  useEffect(() => {
    const pathParts = location.pathname.split('/');
    const langInUrl = pathParts.find(part => part === 'en' || part === 'es');
    if (langInUrl && langInUrl !== language) {
      setLanguage(langInUrl);
    }
  }, [location.pathname]);

  const toggleLanguage = () => {
    setLanguage((prev) => (prev === 'en' ? 'es' : 'en'));
  };

  const t = (key) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

const translations = {
  en: {
    nasaScience: "NASA Science",
    spacePlace: "Space Place",
    tagline: "Explore Earth and Space!",
    viewInSpanish: "Vea en Español",
    viewInEnglish: "View in English",
    searchPlaceholder: "Search Space Place…",
    search: "Search",
    earth: "Earth",
    sun: "Sun",
    solarSystem: "Solar System",
    universe: "Universe",
    scienceTech: "Science & Tech",
    educators: "Educators",
    moon: "Moon",
    play: "Play",
    do: "Do",
    activities: "Activities",
    watch: "Watch",
    words: "Words",
    back: "Back",
    allAboutMoon: "All About the Moon",
    moonPhases: "What Are the Moon's Phases?",
    moonDistance: "How Far Away Is the Moon?",
    skywatchingTips: "Skywatching Tips!",
    nightSkyMonth: "What's up in the night sky this month?",
    checkNasaTips: "Check NASA Tips!",
    launchIntoSpace: "Launch Into Space!",
    learnRockets: "Learn about rockets!",
    playDsn: "Play DSN Uplink!",
    useAntennas: "Use antennas to talk to NASA spacecraft!",
    start: "START!",
    playZone: "Play Zone",
    handsOnLab: "Hands-on Lab",
    scienceFun: "Science fun!",
    quickBites: "Quick Bites",
    spaceWords: "Space Words",
    secretLab: "Secret Lab",
    missionCrate: "Mission Supply Crate",
    aboutUs: "About Us",
    privacy: "Privacy Policy",
    imageUse: "Image Use",
    accessibility: "Accessibility",
    contactNasa: "Contact NASA",
    logEntry: "Log Entry: 6 May 2026",
    skipIntro: "Skip Intro",
    go: "GO!",
    whoosh: "WHOOOOSH!",
    rumble: "RUMBLE...",
    backMissionControl: "Back to Mission Control",
    oopsCosmicCorner: "Oops! This cosmic corner is empty.",
    goBackHome: "Go Back Home",
    cosmicArtTitle: "Show Us Your Cosmic Art!",
    joinChallenge: "Join the Challenge!",
    hallOfFame: "Hall of Cosmic Fame",
    marsPrompt: "What's waiting for you on Mars?",
    artistLabel: "Artist:",
    spinPhases: "SPIN TO SEE PHASES!",
    howMuchMoon: "How much of the Moon can you see tonight?",
    tryDragging: "(Try dragging the Moon!)",
    newMoon: "New Moon",
    waxingCrescent: "Waxing Crescent",
    firstQuarter: "First Quarter",
    waxingGibbous: "Waxing Gibbous",
    fullMoon: "Full Moon",
    waningGibbous: "Waning Gibbous",
    thirdQuarter: "Third Quarter",
    waningCrescent: "Waning Crescent",
    grabSpin: "GRAB & SPIN ME!",
    moonStep0: "Hey there, space explorer! Welcome to the Moon! Have you ever looked up at the night sky and wondered why the Moon seems to change its shape? Sometimes it's a tiny sliver, and other times it's a big, glowing pizza! But guess what? The Moon isn't actually changing shape. We're just seeing different parts lit up by the Sun as it travels around our Earth!",
    moonStep1: "Whoa! Look at that! The Moon is zooming right across your screen! It moves super fast out there in space!",
    moonStep2: "Want to see how the phases work? Try grabbing the Moon and spinning it around! It's like your very own cosmic puppet. I'll give it a spin for you now, just watch!",
    moonStep3: "Wow! Look at that glow! But did you know... the Moon doesn't actually make its own light? It's true! It works just like a giant space mirror, reflecting the bright light coming all the way from the Sun!",
    moonStep4: "Here's a spooky question: Is there a 'dark side' of the Moon? Well... not really! The Moon spins around exactly once for every trip it takes around Earth. That means we always see the exact same side from our backyard! The side we don't see gets just as much sunlight, so scientists prefer to call it the 'far side'.",
    moonStep5: "So, how did this giant rock get up there? Billions of years ago, a massive space object the size of Mars crashed right into Earth! BOOM! That giant splash sent chunks of rock flying into space. Slowly, gravity pulled all those pieces together to build the Moon we see today!",
    moonStep6: "How do we study it? Well, thousands of years ago, people just drew pictures. But today, we use super powerful telescopes and incredible spacecraft! The Moon is actually the only other world humans have ever visited. In 1969, astronauts Neil Armstrong and Buzz Aldrin walked right on that dusty surface!",
    moonStep7: "We know the Moon is covered in craters from space rocks crashing into it over billions of years. Those big dark spots? They're ancient lava that cooled down long ago! There are still so many mysteries left. Maybe YOU will be one of the next explorers to visit the Moon!",
    phasesStep0: "Have you ever looked at the night sky and noticed the Moon seems to change shape? Some nights it's a tiny sliver, and others it's a big, bright circle. These different shapes are called phases of the Moon!",
    phasesStep1: "But here's a secret: the Moon doesn't actually make its own light. Without the Sun, the Moon would be completely dark! What we call 'moonlight' is actually sunlight reflecting off the Moon's surface, like a giant space mirror.",
    phasesStep2: "Sunlight always lights up exactly half of the Moon—the side facing the Sun. The other side is always in shadow. It's just like how Earth has day and night!",
    phasesStep3: "On Earth, our view of that lit-up half changes every night. It all depends on where the Moon is in its orbit around our planet.",
    phasesStep4: "Try spinning the Moon yourself! Watch how the light moves across the surface. When we see the entire lit side, it's a Full Moon. When we see nothing, it's a New Moon!",
    phasesStep5: "There are eight main phases in total: New Moon, Waxing Crescent, First Quarter, Waxing Gibbous, Full Moon, Waning Gibbous, Third Quarter, and Waning Crescent. 'Waxing' means it's getting bigger, and 'Waning' means it's getting smaller.",
    phasesStep6: "The Moon takes about 27.3 days to go around Earth, but the full cycle of phases takes about 29.5 days. That's almost exactly one month! The Moon just keeps on spinning, night after night.",
    distStep0: "Often when we see drawings of the Earth and the Moon, they look really close. But don’t be fooled! They’re actually really far apart. Let's find out exactly how far!",
    distStep1: "The Moon is an average of 238,855 miles (384,400 km) away from Earth. That’s so far that if you could drive a car to the Moon, it would take almost six months of non-stop driving!",
    distStep2: "Want a better way to imagine it? If you lined up Earths one after another between our world and the Moon, you would need 30 Earths to fill the gap! That's a lot of Earths!",
    distStep3: "Why do we say 'average' distance? Well, the Moon's orbit around Earth isn't a perfect circle. It's more like a slightly flattened circle, called an ellipse.",
    distStep4: "When the Moon is at its farthest point, it's about 252,088 miles away—that's almost 32 Earths. When it's closest, it's about 225,623 miles. That's between 28 and 29 Earths!",
    distStep5: "Try moving the Moon yourself! Slide the control to see how far apart Earth and the Moon really are. It surprises most people how much space is between them!",
    distStep6: "You can try this at home! If Earth was a basketball, the Moon would be the size of a tennis ball. To show the real distance, you’d have to place them 23 feet 9 inches apart! That's about 7 big steps!",
    launchStep0: "Ready for liftoff? Launching satellites and spacecraft into space is a huge job! It takes giant rockets and tons of propellant to boost away from Earth's surface.",
    launchStep1: "The big idea behind rockets is Newton's Third Law: For every action, there is an equal and opposite reaction! The exhaust pushing down is the action; the rocket moving up is the reaction!",
    launchStep2: "It's a tug-of-war! To lift off, a rocket creates an upward force called thrust. This thrust must be stronger than Earth's gravity pulling the rocket down.",
    launchStep3: "Speed is the key! A rocket needs to go at least 17,800 miles per hour to reach orbit. That's very, very fast! If it doesn't go fast enough, gravity will pull it back down.",
    launchStep4: "Once in space, a satellite stays in orbit because it has momentum pushing it forward, while gravity pulls it toward Earth. It's a perfect balance that keeps it spinning around our planet!",
    launchStep5: "Want to go further? To reach other planets like Mars, you need even more speed—about 25,000 miles per hour! You also have to wait for a 'Launch Window' when the planets are in just the right spot.",
    launchStep6: "Want to see it in action? Check out this amazing NASA video to see how we actually launch things into the great unknown!",
    neptuneStep0: "Welcome to the edge of the solar system! Neptune is dark, cold, and very windy. It's the eighth and final planet from the Sun—more than 30 times as far as Earth!",
    neptuneStep1: "Neptune is an 'ice giant.' Inside, it's made of a hot, thick soup of water, ammonia, and methane flowing over a solid center about the size of Earth. No solid ground to walk on here!",
    neptuneStep2: "Look at that beautiful blue! Neptune gets its color from methane gas in its atmosphere. It reflects blue light back into space while absorbing red light.",
    neptuneStep3: "Does time fly... or not? A day on Neptune only lasts 16 hours! But Neptune is so far out that it takes 165 Earth years to go around the Sun just once. Imagine waiting that long for your birthday!",
    neptuneStep4: "Hold onto your hats! Neptune has the fastest winds in the solar system, reaching up to 1,200 miles per hour. That's nine times stronger than winds on Earth!",
    neptuneStep5: "Did you know Neptune has rings? There are six of them, but they're very thin and dark, making them super hard to see even with the best telescopes.",
    neptuneStep6: "Only one spacecraft has ever visited Neptune! NASA's Voyager 2 flew by in 1989 and took the amazing photos we use to study this mysterious blue world today.",
    moonTitle: "All About the Moon",
    moonSub: "Why does it look like the Moon is changing shape?",
    moonIntro: "Look up at the night sky and you'll see our closest neighbor: the Moon! We see it change from a tiny sliver to a big, round pizza and back again. But the Moon isn't actually changing—we just see different parts lit up by the Sun as it travels around Earth!",
    moonGlowTitle: "What makes the Moon glow?",
    moonGlowDesc: "The Moon does not shine with its own light. It simply reflects light coming from the Sun.",
    moonDarkSideTitle: "Is there a “dark side” of the Moon?",
    moonDarkSideDesc: "Not really! The Moon spins exactly once for every trip it takes around Earth. This means we always see the same side from our backyard. The side we don't see gets just as much light, so a better name for it is the \"far side.\"",
    moonFormationTitle: "How did the Moon form?",
    moonFormationDesc: "A long time ago, a giant space object the size of Mars crashed into Earth! The massive \"splash\" sent chunks of rock flying into space. Gravity pulled those pieces together to build our Moon.",
    moonStudyTitle: "How do we study the Moon?",
    moonStudyDesc1: "Thousands of years ago, people drew pictures to track the Moon's changes and create calendars. Today, we use powerful telescopes and cool spacecraft! NASA's Lunar Reconnaissance Orbiter has been circling the Moon and sending back data since 2009.",
    moonStudyDesc2: "The Moon is the only other world humans have ever visited. In 1969, Neil Armstrong and Buzz Aldrin were the first people to walk on the dusty surface. Since then, 10 more astronauts have visited to collect rocks and run experiments!",
    moonKnowledgeTitle: "What do we know about the Moon?",
    moonKnowledgeDesc1: "The Moon is covered in craters and dust from space rocks crashing into it over billions of years. Those big dark spots you see? They're called \"maria\" (Latin for seas), but they aren't actually water—they're old lava that cooled down long ago! We also know the Moon has almost no air, weak gravity, and even some frozen water hidden in deep, cold craters.",
    // Journey UI - Launch
    launchTitle: "Launching Into Space",
    launchSub: "How do we get those big rockets up there?",
    launchIntro: "We launch satellites and spacecraft into space by putting them on rockets carrying tons of propellants. The propellants give the rocket enough energy to boost away from Earth’s surface!",
    launchPhysicsTitle: "Rocket Physics",
    launchPhysicsDesc: "For every action, there is an equal and opposite reaction. Exhaust goes down, rocket goes up!",
    launchTugTitle: "The Tug-of-War",
    launchTugDesc: "Thrust must be greater than gravity to lift off. It takes a lot of power to break free!",
    launchSpeedTitle: "Miles Per Hour",
    launchSpeedDesc: "That's how fast you need to go to reach orbit and stay there without falling back down.",
    launchOrbitTitle: "Staying in Orbit",
    launchOrbitDesc1: "The satellite stays in orbit because it still has momentum pulling it in one direction, while Earth’s gravity pulls it in another.",
    launchOrbitDesc2: "This perfect balance keeps it spinning around Earth forever!",
    launchPlanetTitle: "Getting to Other Planets",
    launchPlanetDesc1: "To reach other planets, you need to speed up even more—to about 25,000 mph!",
    launchPlanetDesc2: "You also have to wait for the best time to leave, like when Mars and Earth are closest every two years.",
    launchActionTitle: "Watch it in Action!",
    // Journey UI - Phases
    phasesTitle: "What Are the Moon's Phases?",
    phasesSub: "Why does the Moon change shape?",
    phasesIntro: "If you've looked at the night sky, you've probably noticed that the Moon seems to change shape every night. These different shapes are called phases of the Moon. But guess what? The Moon's shape isn't actually changing—only our view of it is!",
    phasesMirrorTitle: "A Giant Space Mirror",
    phasesMirrorDesc: "The Moon doesn't make its own light. What we call \"moonlight\" is actually just sunlight reflected off the Moon's surface!",
    phasesHalfTitle: "Always Half Lit",
    phasesHalfDesc: "The Sun always lights up exactly one half of the Moon. The other half is always dark, just like Earth has day and night!",
    phasesViewTitle: "Our Changing View",
    phasesViewDesc: "On Earth, our view of the lit part changes every night, depending on where the Moon is in its orbit around Earth.",
    phasesEightTitle: "The Eight Phases",
    phasesListNew: "New: We can't see the Moon at all!",
    phasesListWaxCres: "Waxing Crescent: A thin sliver on the right.",
    phasesListFirst: "First Quarter: Looks like a half-moon.",
    phasesListWaxGib: "Waxing Gibbous: Almost full, getting bigger!",
    phasesListFull: "Full: The whole side is shining bright.",
    phasesListWanGib: "Waning Gibbous: Almost full, getting smaller.",
    phasesListThird: "Third Quarter: Another half-moon, but backwards!",
    phasesListWanCres: "Waning Crescent: A thin sliver on the left.",
    phasesCycleTitle: "The Monthly Cycle",
    phasesCycleDesc1: "It takes the Moon about 27.3 days to orbit Earth. But because of how the sunlight hits the Moon while Earth is moving, it takes about 29.5 days to go from one New Moon to the next.",
    phasesCycleDesc2: "This cycle is where we got the idea for our \"months\"! The Moon is like a giant cosmic clock in the sky.",
    // Journey UI - Distance
    distTitle: "Moon Distance",
    distSub: "How far away is our closest neighbor?",
    distIntro: "You might be surprised! Often when we see drawings of the Earth and the Moon, they look really close together. Don’t be fooled! They’re actually really far apart.",
    distMilesTitle: "Miles Away",
    distMilesDesc: "That is the average distance from Earth to the Moon. It's a very long trip!",
    distThirtyTitle: "30 Earths Wide",
    distThirtyDesc: "You could fit 30 Earth-sized planets in the space between us and the Moon!",
    distOrbitTitle: "Not a Perfect Circle",
    distOrbitDesc: "The Moon orbits Earth in an ellipse (a flattened circle), so it's not always the same distance away.",
    distChangesTitle: "The Distance Changes!",
    distClosest: "CLOSEST (Perigee)",
    distFarthest: "FARTHEST (Apogee)",
    distScaleTitle: "See the Scale!",
    distGripMoon: "Grip the Moon and pull it back!",
    distKeepPulling: "Keep pulling!",
    distTooClose: "Too Close! (Most drawings look like this)",
    distGettingThere: "Getting there...",
    distRealScale: "REAL SCALE! (Look how much empty space!)",
    distHomeTitle: "Try it at Home!",
    distHomeDesc1: "If Earth was the size of a Basketball, the Moon would be the size of a Tennis Ball.",
    distHomeDesc2: "To show the real distance, you would have to place them 23 feet 9 inches apart! That's across a whole room!",
    // Journey UI - Neptune
    neptuneTitle: "All About Neptune",
    neptuneSub: "The Windy Blue Giant",
    neptuneIntro: "Neptune is dark, cold, and very windy. It's the last of the planets in our solar system! It's more than 30 times as far from the Sun as Earth is.",
    neptuneIceTitle: "An Ice Giant",
    neptuneIceDesc: "Neptune is an ice giant. Most of its mass is a hot, dense fluid of \"icy\" materials – water, methane and ammonia – above a small rocky core.",
    neptuneDayTitle: "A Short Day, A Long Year",
    neptuneDayDesc1: "One day on Neptune takes about 16 hours.",
    neptuneDayDesc2: "Neptune makes a complete orbit around the Sun in about 165 Earth years!",
    neptuneAtmosphereTitle: "Blue Atmosphere",
    neptuneAtmosphereDesc: "Neptune’s atmosphere is made mostly of hydrogen and helium, with just a little bit of methane. That methane is what gives Neptune its beautiful blue color!",
    neptuneWindTitle: "Fastest Winds",
    neptuneWindDesc: "Neptune has the fastest winds in the solar system! They can reach speeds of 1,200 miles per hour.",
    neptuneRingsTitle: "Hidden Rings",
    neptuneRingsDesc: "Neptune has at least 5 main rings and 4 more ring arcs. They are very hard to see because they are dark and thin.",
    neptuneVoyagerTitle: "Only One Visitor",
    neptuneVoyagerDesc: "Voyager 2 is the only spacecraft to have visited Neptune up close. It flew by in 1989 on its way out of the solar system.",
  },
  es: {
    nasaScience: "Ciencia de la NASA",
    spacePlace: "Space Place",
    tagline: "¡Explora la Tierra y el espacio!",
    viewInSpanish: "Vea en Español",
    viewInEnglish: "View in English",
    searchPlaceholder: "Buscar en Space Place…",
    search: "Buscar",
    earth: "Tierra",
    sun: "Sol",
    solarSystem: "Sistema Solar",
    universe: "Universo",
    scienceTech: "Ciencia y Tec",
    educators: "Educadores",
    moon: "Luna",
    play: "Jugar",
    do: "Hacer",
    activities: "Actividades",
    watch: "Ver",
    words: "Palabras",
    back: "Atrás",
    allAboutMoon: "Todo sobre la Luna",
    moonPhases: "¿Cuáles son las fases de la Luna?",
    moonDistance: "¿A qué distancia está la Luna?",
    skywatchingTips: "¡Consejos para observar el cielo!",
    nightSkyMonth: "¿Qué hay en el cielo nocturno este mes?",
    checkNasaTips: "¡Ver consejos de la NASA!",
    launchIntoSpace: "¡Lanzamiento al espacio!",
    learnRockets: "¡Aprende sobre cohetes!",
    playDsn: "¡Jugar DSN Uplink!",
    useAntennas: "¡Usa antenas para hablar con las naves de la NASA!",
    start: "¡INICIO!",
    playZone: "Zona de Juegos",
    handsOnLab: "Laboratorio Práctico",
    scienceFun: "¡Diversión Científica!",
    quickBites: "Bocados Rápidos",
    spaceWords: "Palabras Espaciales",
    secretLab: "Laboratorio Secreto",
    missionCrate: "Caja de Suministros de la Misión",
    aboutUs: "Sobre Nosotros",
    privacy: "Política de Privacidad",
    imageUse: "Uso de Imágenes",
    accessibility: "Accesibilidad",
    contactNasa: "Contactar a la NASA",
    logEntry: "Entrada de Registro: 6 de mayo de 2026",
    blastBack: "¡Regresar a la Tierra!",
    startJourney: "Iniciar Viaje",
    stopJourney: "Detener Viaje",
    next: "Siguiente →",
    finish: "¡Terminar!",
    grabSpin: "¡AGÁRRAME Y GÍRAME!",
    skipIntro: "Saltar Intro",
    go: "¡YA!",
    whoosh: "¡WHOOOOSH!",
    rumble: "RUMBLE...",
    backMissionControl: "Volver al Control de la Misión",
    oopsCosmicCorner: "¡Vaya! Este rincón cósmico está vacío.",
    goBackHome: "Volver a Inicio",
    cosmicArtTitle: "¡Muéstranos tu arte cósmico!",
    joinChallenge: "¡Únete al desafío!",
    hallOfFame: "Salón de la Fama Cósmica",
    marsPrompt: "¿Qué te espera en Marte?",
    artistLabel: "Artista:",
    spinPhases: "¡GIRA PARA VER LAS FASES!",
    howMuchMoon: "¿Cuánta Luna puedes ver esta noche?",
    tryDragging: "(¡Intenta arrastrar la Luna!)",
    newMoon: "Luna Nueva",
    waxingCrescent: "Luna Creciente",
    firstQuarter: "Cuarto Creciente",
    waxingGibbous: "Luna Gibosa Creciente",
    fullMoon: "Luna Llena",
    waningGibbous: "Luna Gibosa Menguante",
    thirdQuarter: "Cuarto Menguante",
    waningCrescent: "Luna Menguante",
    moonStep0: "¡Hola, explorador espacial! ¡Bienvenido a la Luna! ¿Alguna vez has mirado el cielo nocturno y te has preguntado por qué la Luna parece cambiar su forma? ¡A veces es una pequeña astilla, y otras veces es una pizza gigante y brillante! Pero, ¿adivina qué? La Luna no está cambiando realmente de forma. ¡Solo estamos viendo diferentes partes iluminadas por el Sol mientras viaja alrededor de nuestra Tierra!",
    moonStep1: "¡Guau! ¡Mira eso! ¡La Luna está pasando zumbando por tu pantalla! ¡Se mueve súper rápido allá afuera en el espacio!",
    moonStep2: "¿Quieres ver cómo funcionan las fases? ¡Intenta agarrar la Luna y girarla! Es como tu propio títere cósmico. ¡Le daré una vuelta por ti ahora, solo mira!",
    moonStep3: "¡Guau! ¡Mira ese brillo! Pero sabías que... ¿la Luna no produce su propia luz? ¡Es verdad! Funciona como un espejo espacial gigante, ¡reflejando la luz brillante que viene desde el Sol!",
    moonStep4: "Aquí hay una pregunta curiosa: ¿Hay un 'lado oscuro' of the Moon? Bueno... ¡no realmente! La Luna gira exactamente una vez por cada viaje que hace alrededor de la Tierra. ¡Eso significa que siempre vemos exactamente el mismo lado desde nuestro patio! El lado que no vemos recibe tanta luz solar, por lo que los científicos prefieren llamarlo el 'lado lejano'.",
    moonStep5: "Entonces, ¿cómo llegó esta roca gigante allí arriba? ¡Hace miles de millones de años, un objeto espacial masivo del tamaño de Marte chocó contra la Tierra! ¡BOOM! Ese choque gigante envió trozos de roca volando al espacio. ¡Lentamente, la gravedad unió todas esas piezas para construir la Luna que vemos hoy!",
    moonStep6: "¿Cómo la estudiamos? Bueno, hace miles de años, la gente solo hacía dibujos. ¡Pero hoy, usamos telescopios súper potentes e increíbles naves espaciales! La Luna es en realidad el único otro mundo que los humanos han visitado. ¡En 1969, los astronautas Neil Armstrong y Buzz Aldrin caminaron sobre esa superficie polvorienta!",
    moonStep7: "Sabemos que la Luna está cubierta de cráteres por rocas espaciales que chocaron contra ella durante miles de millones de años. ¿Esas grandes manchas oscuras? ¡Son lava antigua que se enfrió hace mucho tiempo! Todavía quedan muchos misterios. ¡Tal vez TÚ seas uno de los próximos exploradores en visitar la Luna!",
    moonTitle: "Todo sobre la Luna",
    moonSub: "¿Por qué parece que la Luna cambia de forma?",
    moonIntro: "¡Mira hacia el cielo nocturno y verás a nuestro vecino más cercano: la Luna! Vemos que cambia de una pequeña astilla a una pizza grande y redonda y vuelve a cambiar. Pero la Luna no está cambiando realmente, ¡solo vemos diferentes partes iluminadas por el Sol mientras viaja alrededor de la Tierra!",
    moonGlowTitle: "¿Qué hace que la Luna brille?",
    moonGlowDesc: "La Luna no brilla con luz propia. Simplemente refleja la luz que viene del Sol.",
    moonDarkSideTitle: "¿Hay un \"lado oscuro\" de la Luna?",
    moonDarkSideDesc: "¡No realmente! La Luna gira exactamente una vez por cada viaje que hace alrededor de la Tierra. Esto significa que siempre vemos el mismo lado desde nuestro patio. El lado que no vemos recibe la misma cantidad de luz, por lo que un mejor nombre es el \"lado lejano\".",
    moonFormationTitle: "¿Cómo se formó la Luna?",
    moonFormationDesc: "¡Hace mucho tiempo, un objeto espacial gigante del tamaño de Marte chocó contra la Tierra! El \"salpicón\" masivo envió trozos de roca volando al espacio. La gravedad unió esas piezas para construir nuestra Luna.",
    moonStudyTitle: "¿Cómo estudiamos la Luna?",
    moonStudyDesc1: "Hace miles de años, la gente hacía dibujos para seguir los cambios de la Luna y crear calendarios. ¡Hoy, usamos telescopios potentes y naves espaciales geniales! El Orbitador de Reconocimiento Lunar de la NASA ha estado rodeando la Luna y enviando datos desde 2009.",
    moonStudyDesc2: "La Luna es el único otro mundo que los humanos han visitado. En 1969, Neil Armstrong y Buzz Aldrin fueron las primeras personas en caminar sobre la superficie polvorienta. ¡Desde entonces, 10 astronautas más han visitado para recolectar rocas y realizar experimentos!",
    moonKnowledgeTitle: "¿Qué sabemos sobre la Luna?",
    moonKnowledgeDesc1: "La Luna está cubierta de cráteres y polvo por las rocas espaciales que chocaron contra ella durante miles de millones de años. ¿Esas grandes manchas oscuras que ves? Se llaman \"maria\" (latín para mares), pero no son realmente agua, ¡son lava antigua que se enfrió hace mucho tiempo! También sabemos que la Luna casi no tiene aire, tiene una gravedad débil e incluso algo de agua congelada escondida en cráteres profundos y fríos.",
    moonKnowledgeDesc2: "Todavía quedan muchos misterios por resolver. ¡Tal vez seas uno de los próximos exploradores en visitar la Luna, o incluso Marte!",
    phasesStep0: "¿Alguna vez has mirado el cielo nocturno y has notado que la Luna parece cambiar de forma? Algunas noches es una pequeña astilla y otras es un círculo grande y brillante. ¡Estas diferentes formas se llaman fases de la Luna!",
    phasesStep1: "Pero aquí hay un secreto: la Luna en realidad no produce su propia luz. ¡Sin el Sol, la Luna estaría completamente a oscuras! Lo que llamamos 'luz de luna' es en realidad luz solar que se refleja en la superficie de la Luna, como un espejo gigante en el espacio.",
    phasesStep2: "La luz del Sol siempre ilumina exactamente la mitad de la Luna: el lado que mira al Sol. El otro lado siempre está en sombras. ¡Es igual que la Tierra tiene el día y la noche!",
    phasesStep3: "En la Tierra, nuestra visión de esa mitad iluminada cambia cada noche. Todo depende de dónde se encuentre la Luna en su órbita alrededor de nuestro planeta.",
    phasesStep4: "¡Intenta girar la Luna tú mismo! Observa cómo se mueve la luz por la superficie. Cuando vemos todo el lado iluminado, es Luna Llena. ¡Cuando no vemos nada, es Luna Nueva!",
    phasesStep5: "Hay ocho fases principales en total: Luna Nueva, Luna Creciente, Cuarto Creciente, Luna Gibosa Creciente, Luna Llena, Luna Gibosa Menguante, Cuarto Menguante y Luna Menguante. 'Creciente' significa que se está haciendo más grande, y 'Menguante' significa que se está haciendo más pequeña.",
    phasesStep6: "La Luna tarda unos 27,3 días en dar la vuelta a la Tierra, pero el ciclo completo de fases tarda unos 29,5 días. ¡Eso es casi exactamente un mes! La Luna sigue girando, noche tras noche.",
    distStep0: "A menudo, cuando vemos dibujos de la Tierra y la Luna, parecen estar muy cerca. ¡Pero no te dejes engañar! En realidad están muy lejos. ¡Vamos a descubrir exactamente a qué distancia!",
    distStep1: "La Luna está a una distancia media de 238.855 millas (384.400 km) de la Tierra. ¡Eso es tan lejos que si pudieras conducir un coche hasta la Luna, tardarías casi seis meses de conducción sin parar!",
    distStep2: "¿Quieres una forma mejor de imaginarlo? Si alinearas Tierras una tras otra entre nuestro mundo y la Luna, ¡necesitarías 30 Tierras para llenar el hueco! ¡Son muchas Tierras!",
    distStep3: "¿Por qué decimos distancia 'media'? Bueno, la órbita de la Luna alrededor de la Tierra no es un círculo perfecto. Es más bien como un círculo ligeramente aplanado, llamado elipse.",
    distStep4: "Cuando la Luna está en su punto más lejano, está a unas 252.088 millas de distancia, lo que equivale a casi 32 Tierras. Cuando está más cerca, está a unas 225.623 millas. ¡Eso es entre 28 y 29 Tierras!",
    distStep5: "¡Intenta mover la Luna tú mismo! Desliza el control para ver a qué distancia están realmente la Tierra y la Luna. ¡A la mayoría de la gente le sorprende el espacio que hay entre ellas!",
    distStep6: "¡Puedes probarlo en casa! Si la Tierra fuera un balón de baloncesto, la Luna tendría el tamaño de una pelota de tenis. Para mostrar la distancia real, ¡tendrías que colocarlas a 23 pies y 9 pulgadas de distancia! ¡Eso son unos 7 pasos grandes!",
    launchStep0: "¿Listos para el despegue? ¡Lanzar satélites y naves espaciales al espacio es un trabajo enorme! Se necesitan cohetes gigantes y toneladas de propulsor para impulsarse lejos de la superficie de la Tierra.",
    launchStep1: "La idea más importante detrás de los cohetes es la Tercera Ley de Newton: ¡Para cada acción, hay una reacción igual y opuesta! El escape que empuja hacia abajo es la acción; ¡el cohete que se mueve hacia arriba es la reacción!",
    launchStep2: "¡Es un tira y afloja! Para despegar, un cohete crea una fuerza hacia arriba llamada empuje. Este empuje debe ser más fuerte que la gravedad de la Tierra que tira del cohete hacia abajo.",
    launchStep3: "¡La velocidad es la clave! Un cohete necesita ir al menos a 17.800 millas por hora para alcanzar la órbita. ¡Eso es muy, muy rápido! Si no va lo suficientemente rápido, la gravedad lo volverá a atraer hacia abajo.",
    launchStep4: "Una vez en el espacio, un satélite permanece en órbita porque tiene un impulso que lo empuja hacia adelante, mientras que la gravedad lo atrae hacia la Tierra. ¡Es un equilibrio perfecto que lo mantiene girando alrededor de nuestro planeta!",
    launchStep5: "¿Quieres ir más lejos? Para llegar a otros planetas como Marte, necesitas aún más velocidad: ¡unas 25.000 millas por hora! También hay que esperar a una 'Ventana de Lanzamiento' cuando los planetas están en el lugar adecuado.",
    launchStep6: "¿Quieres verlo en acción? ¡Mira este increíble vídeo de la NASA para ver cómo lanzamos realmente las cosas al gran desconocido!",
    neptuneStep0: "¡Bienvenido al borde del sistema solar! Neptuno es oscuro, frío y muy ventoso. Es el octavo y último planeta desde el Sol: ¡está a más de 30 veces la distancia de la Tierra!",
    neptuneStep1: "Neptuno es un 'gigante de hielo'. En su interior, está hecho de una sopa espesa y caliente de agua, amoníaco y metano que fluye sobre un centro sólido del tamaño de la Tierra. ¡Aquí no hay suelo sólido por el que caminar!",
    neptuneStep2: "¡Mira qué azul más bonito! Neptuno obtiene su color del gas metano de su atmósfera. Refleja la luz azul de vuelta al espacio mientras absorbe la luz roja.",
    neptuneStep3: "¿El tiempo vuela... o no? ¡Un día en Neptuno solo dura 16 horas! Pero Neptuno está tan lejos que tarda 165 años terrestres en dar una sola vuelta al Sol. ¡Imagínate tener que esperar tanto para tu cumpleaños!",
    neptuneStep4: "¡Agárrense los sombreros! Neptuno tiene los vientos más rápidos del sistema solar, alcanzando hasta 1.200 millas por hora. ¡Eso es nueve veces más fuerte que los vientos en la Tierra!",
    neptuneStep5: "¿Sabías que Neptuno tiene anillos? Hay seis, pero son muy finos y oscuros, lo que hace que sean muy difíciles de ver incluso con los mejores telescopios.",
    neptuneStep6: "¡Solo una nave espacial ha visitado Neptuno! La Voyager 2 de la NASA pasó por allí en 1989 y tomó las increíbles fotos que usamos hoy para estudiar este misterioso mundo azul.",
    // Journey UI - Launch (Spanish)
    launchTitle: "Lanzamiento al Espacio",
    launchSub: "¿Cómo subimos esos cohetes tan grandes?",
    launchIntro: "Lanzamos satélites y naves espaciales al espacio poniéndolos en cohetes que transportan toneladas de propulsores. ¡Los propulsores le dan al cohete la energía suficiente para impulsarse lejos de la superficie de la Tierra!",
    launchPhysicsTitle: "Física de Cohetes",
    launchPhysicsDesc: "Para cada acción, hay una reacción igual y opuesta. ¡El escape baja, el cohete sube!",
    launchTugTitle: "El Tira y Afloja",
    launchTugDesc: "El empuje debe ser mayor que la gravedad para despegar. ¡Se necesita mucha potencia para liberarse!",
    launchSpeedTitle: "Millas por Hora",
    launchSpeedDesc: "Esa es la velocidad que necesitas para alcanzar la órbita y quedarte allí sin volver a caer.",
    launchOrbitTitle: "Permanecer en Órbita",
    launchOrbitDesc1: "El satélite permanece en órbita porque tiene un impulso que lo tira en una dirección, mientras que la gravedad de la Tierra lo tira en otra.",
    launchOrbitDesc2: "¡Este equilibrio perfecto lo mantiene girando alrededor de la Tierra para siempre!",
    launchPlanetTitle: "Llegar a Otros Planetas",
    launchPlanetDesc1: "Para llegar a otros planetas, necesitas acelerar aún más, ¡hasta unas 25,000 mph!",
    launchPlanetDesc2: "También tienes que esperar el mejor momento para salir, como cuando Marte y la Tierra están más cerca cada dos años.",
    launchActionTitle: "¡Míralo en Acción!",
    // Journey UI - Phases (Spanish)
    phasesTitle: "¿Cuáles son las fases de la Luna?",
    phasesSub: "¿Por qué la Luna cambia de forma?",
    phasesIntro: "Si has mirado el cielo nocturno, habrás notado que la Luna parece cambiar de forma cada noche. Estas diferentes formas se llaman fases de la Luna. Pero, ¿adivina qué? La forma de la Luna no está cambiando realmente, ¡solo nuestra vista de ella!",
    phasesMirrorTitle: "Un Espejo Espacial Gigante",
    phasesMirrorDesc: "La Luna no produce su propia luz. ¡Lo que llamamos \"luz de luna\" es en realidad solo luz solar reflejada en la superficie de la Luna!",
    phasesHalfTitle: "Siempre Mitad Iluminada",
    phasesHalfDesc: "El Sol siempre ilumina exactamente una mitad de la Luna. La otra mitad siempre está a oscuras, ¡igual que la Tierra tiene el día y la noche!",
    phasesViewTitle: "Nuestra Vista Cambiante",
    phasesViewDesc: "En la Tierra, nuestra vista de la parte iluminada de la Luna cambia cada noche, dependiendo de dónde se encuentre la Luna en su órbita alrededor de la Tierra.",
    phasesEightTitle: "Las Ocho Fases Lunares",
    phasesListNew: "Nueva: ¡No podemos ver la Luna en absoluto!",
    phasesListWaxCres: "Creciente: Una fina astilla a la derecha.",
    phasesListFirst: "Cuarto Creciente: Parece una media luna.",
    phasesListWaxGib: "Gibosa Creciente: ¡Casi llena, creciendo!",
    phasesListFull: "Llena: Todo el lado brilla intensamente.",
    phasesListWanGib: "Gibosa Menguante: Casi llena, haciéndose más pequeña.",
    phasesListThird: "Cuarto Menguante: ¡Otra media luna, pero al revés!",
    phasesListWanCres: "Menguante: Una fina astilla a la izquierda.",
    phasesCycleTitle: "El Ciclo Mensual",
    phasesCycleDesc1: "La Luna tarda unos 27.3 días en orbitar la Tierra. Sin embargo, debido a cómo la luz solar golpea la Luna mientras la Tierra se mueve, tarda unos 29.5 días en pasar de una Luna Nueva a la siguiente.",
    phasesCycleDesc2: "¡De este ciclo sacamos la idea de nuestros \"meses\"! La Luna es como un reloj cósmico gigante en el cielo.",
    // Journey UI - Distance (Spanish)
    distTitle: "Distancia a la Luna",
    distSub: "¿A qué distancia está nuestro vecino más cercano?",
    distIntro: "¡Podría sorprenderte! A menudo, cuando vemos dibujos de la Tierra y la Luna, parecen estar muy cerca. ¡No te dejes engañar! En realidad están muy lejos.",
    distMilesTitle: "Millas de Distancia",
    distMilesDesc: "Esa es la distancia promedio de la Tierra a la Luna. ¡Es un viaje muy largo!",
    distThirtyTitle: "30 Tierras de Ancho",
    distThirtyDesc: "¡Podrías encajar 30 planetas del tamaño de la Tierra en el espacio entre nosotros y la Luna!",
    distOrbitTitle: "No es un Círculo Perfecto",
    distOrbitDesc: "La Luna orbita la Tierra en una elipse (un círculo aplanado), por lo que no siempre está a la misma distancia.",
    distChangesTitle: "¡La Distancia Cambia!",
    distClosest: "MÁS CERCA (Perigeo)",
    distFarthest: "MÁS LEJOS (Apogeo)",
    distScaleTitle: "¡Mira la Escala!",
    distGripMoon: "¡Agarra la Luna y tira de ella!",
    distKeepPulling: "¡Sigue tirando!",
    distTooClose: "¡Demasiado Cerca! (La mayoría de los dibujos se ven así)",
    distGettingThere: "Ya casi...",
    distRealScale: "¡ESCALA REAL! (¡Mira cuánto espacio vacío!)",
    distHomeTitle: "¡Pruébalo en Casa!",
    distHomeDesc1: "Si la Tierra fuera del tamaño de un Balón de Baloncesto, la Luna sería del tamaño de una Pelota de Tenis.",
    distHomeDesc2: "Para mostrar la distancia real, ¡tendrías que colocarlos a 23 pies y 9 pulgadas de distancia! ¡Eso es a través de toda una habitación!",
    // Journey UI - Neptune (Spanish)
    neptuneTitle: "Todo sobre Neptuno",
    neptuneSub: "El Gigante Azul Ventoso",
    neptuneIntro: "Neptuno es oscuro, frío y muy ventoso. ¡Es el último de los planetas de nuestro sistema solar! Está más de 30 veces más lejos del Sol que la Tierra.",
    neptuneIceTitle: "Un Gigante de Hielo",
    neptuneIceDesc: "Neptuno es un gigante de hielo. La mayor parte de su masa es un fluido caliente y denso de materiales \"helados\" (agua, metano y amoníaco) sobre un pequeño núcleo rocoso.",
    neptuneDayTitle: "Un Día Corto, Un Año Largo",
    neptuneDayDesc1: "Un día en Neptuno dura unas 16 horas.",
    neptuneDayDesc2: "¡Neptuno hace una órbita completa alrededor del Sol en unos 165 años terrestres!",
    neptuneAtmosphereTitle: "Atmósfera Azul",
    neptuneAtmosphereDesc: "La atmósfera de Neptuno está hecha principalmente de hidrógeno y helio, con solo un poco de metano. ¡Ese metano es lo que le da a Neptuno su hermoso color azul!",
    neptuneWindTitle: "Vientos más Rápidos",
    neptuneWindDesc: "¡Neptuno tiene los vientos más rápidos del sistema solar! Pueden alcanzar velocidades de 1.200 millas por hora.",
    neptuneRingsTitle: "Anillos Ocultos",
    neptuneRingsDesc: "Neptuno tiene al menos 5 anillos principales y 4 arcos de anillos más. Son muy difíciles de ver porque son oscuros y delgados.",
    neptuneVoyagerTitle: "Un Solo Visitante",
    neptuneVoyagerDesc: "Voyager 2 es la única nave espacial que ha visitado Neptuno de cerca. Pasó volando en 1989 en su camino fuera del sistema solar.",
  }
};


